// ===== LEXVAULT BOOK DATABASE =====
const BOOKS = [
  {
    id: 1,
    title: "Federal Rules of Evidence 2025",
    category: "Evidence",
    cat: "evidence",
    desc: "Complete annotated guide to FRE with leading case analysis, objections handbook, and trial practice tips.",
    price: 14,
    emoji: "⚖️",
    color: "#1e3a5f",
    featured: true,
    pages: 312,
    format: "PDF",
    author: "Prof. James Hartley",
    updated: "2025"
  },
  {
    id: 2,
    title: "Constitutional Law: Modern Doctrine",
    category: "Constitutional",
    cat: "constitutional",
    desc: "First Amendment, due process, equal protection through the lens of contemporary Supreme Court decisions.",
    price: 15,
    emoji: "🏛️",
    color: "#2d1b4e",
    featured: true,
    pages: 428,
    format: "PDF",
    author: "Dr. Sarah Chen",
    updated: "2025"
  },
  {
    id: 3,
    title: "Civil Procedure: A Practical Guide",
    category: "Civil Procedure",
    cat: "civil",
    desc: "Federal Rules of Civil Procedure, discovery strategy, motion practice, and appellate procedure explained.",
    price: 12,
    emoji: "📋",
    color: "#1a3a2a",
    featured: true,
    pages: 256,
    format: "PDF",
    author: "Hon. Robert Ames (Ret.)",
    updated: "2024"
  },
  {
    id: 4,
    title: "Criminal Defense: Strategy & Tactics",
    category: "Criminal Law",
    cat: "criminal",
    desc: "From arraignment to appeal — a complete criminal defense playbook for public defenders and private attorneys.",
    price: 13,
    emoji: "🔏",
    color: "#3a1a1a",
    featured: true,
    pages: 384,
    format: "PDF",
    author: "Maria Vasquez, Esq.",
    updated: "2025"
  },
  {
    id: 5,
    title: "Corporate M&A: Legal Framework",
    category: "Corporate",
    cat: "corporate",
    desc: "Mergers, acquisitions, due diligence, representations and warranties — the full transactional legal lifecycle.",
    price: 15,
    emoji: "💼",
    color: "#2a2a1a",
    featured: false,
    pages: 340,
    format: "PDF",
    author: "Thomas Whitfield",
    updated: "2025"
  },
  {
    id: 6,
    title: "Patent Litigation Handbook",
    category: "Intellectual Property",
    cat: "ip",
    desc: "Claim construction, IPR proceedings, ITC actions, and district court patent litigation strategy.",
    price: 14,
    emoji: "💡",
    color: "#1a2a3a",
    featured: false,
    pages: 298,
    format: "PDF",
    author: "Dr. Linda Park",
    updated: "2024"
  },
  {
    id: 7,
    title: "Family Law Across States",
    category: "Family Law",
    cat: "family",
    desc: "Divorce, custody, child support, adoption — comparative analysis of law across all 50 US states.",
    price: 11,
    emoji: "👨‍👩‍👧",
    color: "#3a1a2d",
    featured: false,
    pages: 220,
    format: "PDF",
    author: "Karen Mitchell, JD",
    updated: "2025"
  },
  {
    id: 8,
    title: "Securities Regulation & Compliance",
    category: "Corporate",
    cat: "corporate",
    desc: "SEC rules, insider trading laws, disclosure obligations, and enforcement actions for corporate counsel.",
    price: 15,
    emoji: "📊",
    color: "#1a3a35",
    featured: false,
    pages: 310,
    format: "PDF",
    author: "William Stone, Esq.",
    updated: "2025"
  },
  {
    id: 9,
    title: "Immigration Law: Current Practice",
    category: "Immigration",
    cat: "immigration",
    desc: "Visas, green cards, deportation defense, asylum proceedings, and USCIS practice under current policy.",
    price: 13,
    emoji: "✈️",
    color: "#2a1a3a",
    featured: false,
    pages: 275,
    format: "PDF",
    author: "Sofia Reyes, Esq.",
    updated: "2025"
  },
  {
    id: 10,
    title: "Employment Law Essentials",
    category: "Employment",
    cat: "employment",
    desc: "Title VII, ADA, FMLA, non-compete agreements, and wrongful termination — employer and employee perspectives.",
    price: 12,
    emoji: "👔",
    color: "#3a2a1a",
    featured: false,
    pages: 240,
    format: "PDF",
    author: "Dr. Paul Nkemelu",
    updated: "2024"
  },
  {
    id: 11,
    title: "Bankruptcy & Restructuring Law",
    category: "Bankruptcy",
    cat: "bankruptcy",
    desc: "Chapter 7, 11, 13 proceedings, automatic stay, preference actions, and plan confirmation strategy.",
    price: 14,
    emoji: "⚡",
    color: "#1e2a1a",
    featured: false,
    pages: 330,
    format: "PDF",
    author: "Gregory Hart, Esq.",
    updated: "2025"
  },
  {
    id: 12,
    title: "Environmental Law & Regulation",
    category: "Environmental",
    cat: "environmental",
    desc: "EPA regulations, NEPA, Clean Air and Water Acts, toxic tort litigation, and climate policy updates.",
    price: 10,
    emoji: "🌿",
    color: "#1a3a1a",
    featured: false,
    pages: 195,
    format: "PDF",
    author: "Dr. Amy Torres",
    updated: "2024"
  }
];

// Export for use across scripts
if (typeof module !== 'undefined') module.exports = BOOKS;
